[package]
name = "backend"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]


[dependencies]
chrono.workspace = true
diesel.workspace = true
ft-sdk.workspace = true
http.workspace = true
serde_json.workspace = true
