name: Upload lets-update-template to FifthTry

on:
  push:
    branches: [ main ]
    paths:
      - lets-update-template.fifthtry.site/**
      - .github/workflows/template-to-ft.yml


jobs:
  upload-to-fifthtry:
    runs-on: ubuntu-latest
    env:
      FIFTHTRY_SITE_WRITE_TOKEN: ${{ secrets.FT_LETS_UPDATE_TEMPLATE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: sh -c "$(curl -fsSL https://fastn.com/install.sh)"

# let's publish this only after there is some stability on the schema
#      - name: Upload to FifthTry using fastn
#        run: cd lets-update-template.fifthtry.site/ && fastn upload lets-update-template
